# Generated by Django 4.0.6 on 2022-08-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_client_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientRusZam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
